### ISSUE TITLE
Unable to generate/retrieve latest png via revision=0

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/wikipathways.org#35]
Seems like the shortcut designation for "latest version" isn't working with latest Pathway.php code.

This call works:
https://webservice.wikipathways.org/getPathwayAs?fileType=png&pwId=WP566&revision=95726

But this call does not:
https://webservice.wikipathways.org/getPathwayAs?fileType=png&pwId=WP566&revision=0

They should return the exact same result.

Full stack trace:
error 500 Unable to get pathway: exception 'Exception' with message 'Unable to convert to png: ** (inkscape:5130): CRITICAL **: Inkscape::XML::Document* sp_repr_read_file(const gchar*, const gchar*): assertion 'Inkscape::IO::file_test( filename, G_FILE_TEST_EXISTS )' failed ** (inkscape:5130): CRITICAL **: Inkscape::XML::Document* sp_repr_read_file(const gchar*, const gchar*): assertion 'Inkscape::IO::file_test( filename, G_FILE_TEST_EXISTS )' failed ** (inkscape:5130): WARNING **: Specified document /var/www/wikipathways/images/e/e4/WP566.svg cannot be opened (does not exist or not a valid SVG file) Command: inkscape -z -b white -w 1000 -f '/var/www/wikipathways/images/e/e4/WP566.svg' -e '/var/www/wikipathways/images/3/33/WP566.png' 2>&1' in /var/www/wikipathways/wpi/extensions/Pathways/Pathway.php:1324 Stack trace: #0 /var/www/wikipathways/wpi/extensions/Pathways/Pathway.php(1123): Pathway->savePngCache() #1 /var/www/wikipathways/wpi/extensions/Pathways/Pathway.php(640): Pathway->updateCache('png') #2 /var/www/wikipathways/wpi/webservice2.0/webservice.php(310): Pathway->getFileLocation('png') #3 [internal function]: getPathwayAs('png', 'WP566', '0') #4 /var/www/wikipathways/wpi/webservice2.0/webservice.lib.php(402): ReflectionFunction->invokeArgs(Array) #5 /var/www/wikipathways/wpi/webservice2.0/webservice.lib.php(263): BCWebService->executeMethod() #6 /var/www/wikipathways/wpi/webservice2.0/index.php(172): BCWebService->listen() #7 {main} : Receiver :

**Comment by AlexanderPico** [comment]
Fixed by adding missing if statement to getPathwayAs in webservices2.0
